POST {{host}}/accounts/create
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Test account 1",
    "currencyId": "bde4a5c7-d3e3-4725-a28e-ff834796e47e",
    "initialBalance": 0
}