@host = https://localhost:5001

GET {{host}}/accounts/getById?accountId=1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1NjkyNDQ1ZS05MDE2LTQwYjYtYjQzNy03YTNjMDJhMDVjMmEiLCJzdWIiOiJkMTgyNDFhMS1lNjE3LTRkNzktYjczYS1mNDc0OGE3OTMyYTUiLCJlbWFpbCI6ImtvbGV2OTYwNUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzE0MTQxNDc0LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.lljlBpm1cnyhE19nOku8pAujHVn52Jgp6jb4mRKUWU4
