# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  budgetweb:
    image: budgetweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentDocker
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
