GET {{host}}/accounts?includeHidden=false
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJjZTBiY2ZkMC0wNWFkLTRiNGEtOTlhMi0zY2QyNWU0NzJiYzEiLCJzdWIiOiIyMzY1NzJkMi03OTAwLTRiNTItOGVjNi1iNmVkODVhODI4MDUiLCJlbWFpbCI6ImtvbGV2OTYwNUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzY5MjA2OTI2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.7L13kOASMCxE7WEoOwWQCfWMVCWqe5iPvSw3KBE-WIM