@host = https://localhost:5001

GET {{host}}/categories/getById?categoryId=1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlOTVjM2UyMC04NjBkLTRkZmYtYjY0Zi1mYjFlNDExZWMxMjciLCJzdWIiOiJkMTgyNDFhMS1lNjE3LTRkNzktYjczYS1mNDc0OGE3OTMyYTUiLCJlbWFpbCI6ImtvbGV2OTYwNUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzE1NzIwODg2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.-K0dT6fTCCVs2_09uWzqpUBXjVbcmbGXOaCyTOg7aWA