@host = https://localhost:5001

GET {{host}}/Account/GetAll
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiMjYwODBkMS0yY2YzLTQ3NDctYTAxYS0xYjVlODQ0NDgxNzUiLCJzdWIiOiIxZWVkZmMwNC00NGFlLTQ3OGMtYmQwOC04YTJmMDM1NWQ0MWIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNjgxNjcxNTM5LCJpc3MiOiJCdWRnZXQiLCJhdWQiOiJCdWRnZXQifQ.-lHHPRMTbTFn3rtWW9DCG1VPQl8RW3RcMgfvljw3WPo