# @name login
POST {{host}}/Authentication/Login
Content-Type: application/json

{
    "email": "kolev9605@gmail.com",
    "password": "kolev9605@gmail.com"
}

###

GET {{host}}/accounts/2161d8c8-e84f-4870-b241-353624b888e3
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###

GET {{host}}/accounts?includeHidden=false
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###

POST {{host}}/accounts
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "name": "Test account 2",
    "currencyId": "adc2b74c-15d1-4026-a4c7-d1bc994f35c3",
    "paymentTypeId": "617b69ac-57c5-4286-9188-80bc850352da",
    "initialBalance": 0
}

###

DELETE {{host}}/accounts/37e39211-f0d8-4e60-b838-2e880f567f4a
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###

PUT {{host}}/accounts
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "id": "2161d8c8-e84f-4870-b241-353624b888e3",
    "name": "Test account 1 (updated)",
    "currencyId": "adc2b74c-15d1-4026-a4c7-d1bc994f35c3",
    "paymentTypeId": "617b69ac-57c5-4286-9188-80bc850352da",
    "initialBalance": 0
}